<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title><?php echo isset($categoria) ? 'Editar Categoría' : 'Agregar Categoría'; ?></title>
    <link href="/DivainParfums/public/css/style.css" rel="stylesheet">
</head>
<body>
    <h1><?php echo isset($categoria) ? 'Editar Categoría' : 'Agregar Categoría'; ?></h1>
    <form action="/DivainParfums/categoria/<?php echo isset($categoria) ? 'actualizar' : 'guardar'; ?>" method="POST">
        <?php if (isset($categoria)): ?>
            <input name="id_categoria" value="<?php echo htmlspecialchars($categoria['id_categoria']); ?>" type="hidden">
        <?php endif; ?>
        <label for="nombre_categoria">Nombre de la Categoría:</label>
        <input name="nombre_categoria" value="<?php echo isset($categoria) ? htmlspecialchars($categoria['nombre_categoria']) : ''; ?>" id="nombre_categoria" required><br>
        <button type="submit"><?php echo isset($categoria) ? 'Actualizar Categoría' : 'Guardar Categoría'; ?></button>
    </form>
    <a href="/DivainParfums/categoria">Volver al listado de categorías</a>
</body>
</html>
