<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title><?php echo isset($ingrediente) ? 'Editar Ingrediente' : 'Agregar Ingrediente'; ?></title>
    <link href="/DivainParfums/public/css/style.css" rel="stylesheet">
</head>
<body>
    <h1><?php echo isset($ingrediente) ? 'Editar Ingrediente' : 'Agregar Ingrediente'; ?></h1>
    <form action="/DivainParfums/ingrediente/<?php echo isset($ingrediente) ? 'actualizar' : 'guardar'; ?>" method="POST">
        <?php if (isset($ingrediente)): ?>
            <input name="id_ingrediente" value="<?php echo htmlspecialchars($ingrediente['id_ingrediente']); ?>" type="hidden">
        <?php endif; ?>
        <label for="nombre_ingrediente">Nombre del Ingrediente:</label>
        <input name="nombre_ingrediente" value="<?php echo isset($ingrediente) ? htmlspecialchars($ingrediente['nombre_ingrediente']) : ''; ?>" id="nombre_ingrediente" required><br>
        <label for="descripcion">Descripción:</label>
        <textarea id="descripcion" name="descripcion" required><?php echo isset($ingrediente) ? htmlspecialchars($ingrediente['descripcion']) : ''; ?></textarea><br>
        <button type="submit"><?php echo isset($ingrediente) ? 'Actualizar Ingrediente' : 'Guardar Ingrediente'; ?></button>
    </form>
    <a href="/DivainParfums/ingrediente">Volver al listado de ingredientes</a>
</body>
</html>
