<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Listado de Ingredientes</title>
    <link href="/DivainParfums/public/css/style.css" rel="stylesheet">
</head>
<body>
    <h1>Listado de Ingredientes</h1>
    <a href="/DivainParfums/ingrediente/agregar">Agregar Ingrediente</a>
    <ul class="productos">
        <?php foreach ($ingredientes as $ingrediente): ?>
            <li><?php echo htmlspecialchars($ingrediente['nombre_ingrediente']); ?> - <?php echo htmlspecialchars($ingrediente['descripcion']); ?>
                <a href="/DivainParfums/ingrediente/editar/<?php echo $ingrediente['id_ingrediente']; ?>">Editar</a> 
                <a href="/DivainParfums/ingrediente/eliminar/<?php echo $ingrediente['id_ingrediente']; ?>">Eliminar</a>
            </li>
        <?php endforeach; ?>
    </ul>
    <a href="/DivainParfums/producto">Volver al menú</a>
    <?php include 'footer.phtml'; ?>
</body>
</html>
