<!doctype html>
<html lang="es">
<?php include 'header.phtml'; ?>
<body>
    <h1>Listado de Productos</h1>
    <a href="/DivainParfums/producto/agregar">Agregar Producto</a>
    <ul class="productos">
        <?php foreach ($productos as $producto): ?>
            <li><?php echo htmlspecialchars($producto['nombre_producto']); ?> - <?php echo htmlspecialchars($producto['nombre_categoria']); ?> - $<?php echo htmlspecialchars($producto['precio']); ?>
                <a href="/DivainParfums/producto/<?php echo $producto['id_producto']; ?>">Ver Detalle</a> 
                <a href="/DivainParfums/producto/editar/<?php echo $producto['id_producto']; ?>">Editar</a> 
                <a href="/DivainParfums/producto/eliminar/<?php echo $producto['id_producto']; ?>">Eliminar</a>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php include 'footer.phtml'; ?>
</body>
</html>
