<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Login de Administrador</title>
    <link href="/DivainParfums/public/css/style.css" rel="stylesheet">
</head>
<body>
    <h1>Login de Administrador</h1>
    <form action="/DivainParfums/login" method="POST">
        <label for="username">Usuario:</label> 
        <input name="username" id="username" required type="text"><br>
        <label for="password">Contraseña:</label> 
        <input name="password" id="password" required type="password"><br>
        <button type="submit">Iniciar Sesión</button>
    </form>
</body>
</html>
